@startuml space-spiel-engine
/'
engine.puml: Space spiel UML class diagram for different logic.
Copyright (C) 2026  Vladyslav Tupikin
Contact: vladtupikin7@gmail.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
'/

class RenderEngine <<singleton>> {
    -objectsToRender : Renderer[]
    -instance : RenderEngine
    --
    -Renderer()
    .. General ..
    + toString() : String
    + renderObjects() : void
    + addRenderObj() : boolean
    + removeRenderObj() : boolean
    .. Getters / Setters ..
    +getInstance() : RenderEngine
}

class CollisionModel {
    - id: int
    - radius: int
    - center: Point
    --
    - CollisionModel()
    .. General ..
    + toString() : String
    .. Getters / Setters ..
    + getID() : int
}

class CollisionEngine <<singleton>> {
    - instance : CollisionEngine
    - collisionObjects: CollisionModel[]
    - listeners: List<OnCollisionListener>
    --
    - CollisionEngine()
    .. General ..
    + toString() : String
    + addCollisionObject() : boolean
    + removeCollisionObject() : boolean
    .. Getters / Setters ..
    + getInstance() : CollisionEngine
    .. Event Listener ..
    + addMoveListener(l: OnCollisionListener): void
    + removeMoveListener(l: OnCollisionListener): void
    .. Events ..
    + onPlayerMove(e: PlayerMoveEvent): void
    + onEnemyMove(e: EnemyMoveEvent): void
    + onPistolGunFire(e: PistolGunFireEvent): void
}

class PhysicsEngine <<singleton>> {
    - instance : PhysicsEngine
    .. Getters / Setters ..
    + getInstance() : PhysicsEngine
}

@enduml
